#! /bin/bash

python_dir=/usr/local/bin/python3
bird_dir=/home/sigongweb/server/project/MariaBird

case "$1" in
  start|START)
    echo "Starting MariaBird..........."
    # start Daemon
    $python_dir $bird_dir start &
  ;;
  stop|STOP)
    echo "Stopping MariaBird..........."
    # stop Daemon
    $python_dir $bird_dir stop
  ;;
  *)
    echo "Usage /etc/init.d/MariaBird {start|stop|status}"
  ;;
esac

exit 0